Bugfix/css bio speakers
gencat/participa-catalunya pull request #96
Opened 2021-09-23 08:17 UTC by spuigmitjadxc

Fix on style of speakers when there is more than 4:
![image](https://user-images.githubusercontent.com/64258984/134475087-7d8eb86f-72e0-488b-8994-cd591c6d2d98.png)

2021-09-23 14:36 UTC, LauraJaimeC requested changes
Hi!! Good job :)

Web view is correct, but in mobile view is broken:

This is in production:

![Captura de pantalla de 2021-09-23 16-32-06](https://user-images.githubusercontent.com/75725233/134527412-a14a1e1b-5661-4b0d-87e1-4cc405f82b24.png)


and this is in local with this changes

![Captura de pantalla de 2021-09-23 16-31-52](https://user-images.githubusercontent.com/75725233/134527426-b2f0e738-c8a0-4c02-9a22-d9cf9959a988.png)

![Captura de pantalla de 2021-09-23 16-31-55](https://user-images.githubusercontent.com/75725233/134527444-0c54afef-3f33-444c-848f-4b9cf789e7f5.png)


Maybe you can applied this changes only for web view.

2021-09-24 12:10 UTC, spuigmitjadxc commented
@LauraJaimeC changed to use @include breakpoint(medium) as is done in decidim:
[https://github.com/decidim/decidim/blob/develop/decidim-core/app/packs/stylesheets/decidim/modules/_conference-speaker.scss](https://github.com/decidim/decidim/blob/develop/decidim-core/app/packs/stylesheets/decidim/modules/_conference-speaker.scss)

2021-09-27 06:12 UTC, LauraJaimeC approved these changes

2021-09-27 06:12 UTC, LauraJaimeC commented
> @LauraJaimeC changed to use @include breakpoint(medium) as is done in decidim:
> https://github.com/decidim/decidim/blob/develop/decidim-core/app/packs/stylesheets/decidim/modules/_conference-speaker.scss

Great!! Approved :)

2021-09-27 08:14 UTC, merged